# Generated by Django 4.0.4 on 2022-06-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_remove_collection_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очередь в списке'),
        ),
    ]
