# Generated by Django 4.0.4 on 2022-06-24 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_collection_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcollection',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_collections', to='mainapp.collection', verbose_name='Категория'),
        ),
    ]
