# Generated by Django 4.0.4 on 2022-07-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_subcollection_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcollection',
            name='order_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Очередь в списке'),
        ),
    ]
